### ISSUE TITLE
Type "Ahorn.FriendlyCaptcha:Captcha" not found

### ISSUE THREAD

**Issue by TobiaV** [ahornlabs/friendly-captcha-neos#2]
I am assuming this is no longer maintained. the composer require command is wrong. it is "composer require ahorn/friendlycaptcha"

The main issue i am facing is that it throws the Error after install: Type "Ahorn.FriendlyCaptcha:Captcha" not found.

It may also be a simple error on my end.

**Comment by koehlerannkathrin** [comment]
A different preset (not general) was probably used, which is why the nodetype could not be found.
Definition for general preset can be found [here](https://github.com/ahornlabs/friendly-captcha-neos/blob/main/Configuration/Settings.yaml)
